<?xml version="1.0"?>
<signature createdate="2010-07-07 13:31:51 / 1278502311"><signature_pic_lvlsea>Sea</signature_pic_lvlsea><signature_pic_lvlland>Land</signature_pic_lvlland><signature_slots>Character {1}</signature_slots><signature_selectlang_title>Language:</signature_selectlang_title><signature_selectlang_default>Default: preferred language of the user</signature_selectlang_default><signature_create_bcccode>BB-Code (forum use)</signature_create_bcccode><signature_create_htmlcode>HTML-Code</signature_create_htmlcode><signature_create_subtitle>Signature: {1} created by {2}</signature_create_subtitle><signature_instruction_howto>[b]How to use:[/b]&#xD;
First of all, you need to know how many characters you would like to display on your signature.&#xD;
Write the names of your character(s) into the boxe(s). (You don't need to fill all of them)&#xD;
Select a display language&#xD;
Click on : Create your signature!&#xD;
After it you will see an overview of all signatures which have your specified amount of slots or more.&#xD;
&#xD;
The amount of the boxes depends if there is a template which can handle the amount of characters.&#xD;
E.g. if there are only three boxes and you would like to have a signatures with four or more slots please read the post&#xD;
[i][url=http://florensia-forumurl/thread-3507.html]"How to create your own Signature"[/url][/i]&#xD;
and send your work to an admin or publish it on our forum.&#xD;
&#xD;
** Your signature will be automatically updated during night. A delay is then possible between the displayed level and your actual level.&#xD;
</signature_instruction_howto><signature_instruction_advancedhint>[b]Hint for advanced users:[/b]&#xD;
You can leave free slots between characters to get a "placeholder".&#xD;
Also you can switch names to reorder the display of your characters on the signature.</signature_instruction_advancedhint><signature_slotsoverviewtitle>[b]We have:[/b]</signature_slotsoverviewtitle><signature_displayall>Display all signatures even with more slots</signature_displayall><signature_docreate>Create your signature!</signature_docreate><signature_slotsoverviewrow>{1} Template(s) with {2} Slot(s)</signature_slotsoverviewrow><signature_create_backgroundupload_error_notice>Upload of your background was not successfully.</signature_create_backgroundupload_error_notice><signature_create_savetemplate_error_notice>An error occurred while trying to save your template.</signature_create_savetemplate_error_notice><signature_create_template_error_notice>Your template has some errors. Please fix them so I will be able to save it.</signature_create_template_error_notice><signature_create_characterslots_notice>Slots to specify your characters will be available as soon as you create the needed &lt;char&gt; tags</signature_create_characterslots_notice><signature_create_characterslots_templateerror_notice>Slots to specify your characters will be available as soon as the template can be parsed</signature_create_characterslots_templateerror_notice><signature_create_signaturecode>This code will always point to your signature you have created here.</signature_create_signaturecode><signature_create_refresh>Refresh</signature_create_refresh><signature_create_popup_wheretouse>Where to use:</signature_create_popup_wheretouse><signature_create_popup_madatorytags>Mandatory tags</signature_create_popup_madatorytags><signature_create_popup_optionaltags>Optional tags:</signature_create_popup_optionaltags><signature_create_pagedescription>[b]On this site you can create your own signature.[/b]&#xD;
Please edit your template carefully because no backups will be made and there is no undo.&#xD;
If you have any questions how this all works read the [url=http://florensia-forumurl/thread-3507.html]"How to create your own Signature"[/url] in the forum and feel free to ask.&#xD;
Once finished your template you can contact an administrator or publish it on the forum yourself. If it's nicely made and gets good feedback we will include it to the official signature generator so all users can use it!</signature_create_pagedescription><signature_create_backgroundupload>Upload a new background:</signature_create_backgroundupload><signature_create_backgroundupload_data>Only gif, png or jpg - max. width: 700px, max. height: 700px</signature_create_backgroundupload_data><signature_create_template_title>Template</signature_create_template_title><signature_create_colorpicker_title>Colorpicker</signature_create_colorpicker_title><signature_create_additionalobjects_title>Additional objects available</signature_create_additionalobjects_title><signature_create_additionalobjects_notice>Hover over the symbols to get more information</signature_create_additionalobjects_notice><signature_create_fonthelper_title>Font-Helper</signature_create_fonthelper_title><signature_create_getcoordinates>Click on the picture to get the exact coordinates:</signature_create_getcoordinates></signature>
