<?xml version="1.0"?>
<donate createdate="2010-11-14 16:06:24 / 1289750784"><donate_donatorlist_title>Lista dei generosi donatori</donate_donatorlist_title><donate_notice>Questo sito &#xE8; un progetto privato e i costi per il suo mantenimento sono abbastanza alti (circa {1}/al mese).&#xD;
Ci farebbe piacere che gli utilizzatori del sito non lo visitassero e basta ma che possano in qualche modo contribuire a mantenere vivo questo progetto.&#xD;
Sarebbe fantastico se poteste contribuire in qualche modo via paypal cliccando nell'immagine qua sotto. Grazie!</donate_notice><donate_donatorlist_date>[b]{1}[/b] da {2} su {3}</donate_donatorlist_date><donate_startpage_title>FloBase &#xE8; qui quando hai bisogno - adesso FloBase ha bisogno di te!</donate_startpage_title><donate_startpage_donatetext>Vorrei vivamente ringrazie i generosi donatori - il traguardo dei 200&#x20AC; &#xE8; stato raggiunto e superato.&#xD;
Troverete la lista dei donatori sulla destra in ordine di grandezza della donazione e tempo della donazione.&#xD;
Per maggiori informazioni (come ad esempio perch&#xE8; proprio 200&#x20AC; e l'apertura di nuovi server leggete le novit&#xE0; sul forum).&#xD;
Se qualcuno volesse donare qualcosa perfavore non dimenticatevi di segnalare il vostro nickname alla fine della transazione ed io provveder&#xF2; ad aggiungervi alla lista il prima possibile.&#xD;
Ancora: Grazie mille!&#xD;
</donate_startpage_donatetext><donate_startpage_bottomnotice>Le donazioni saranno usate unicamente per Florensia Base! [b]Gli sponsor sono benvenuti![/b] Contatta webmaster[at]florensia-base[dot]com. (in inglese)</donate_startpage_bottomnotice><donate_paypalfees>Pagamento con Paypal</donate_paypalfees><donate_linktodonatepage>Ti piace Florensia Base? - Per favore supportaci con una donazione.</donate_linktodonatepage><donate_currentmonth_title>Mese corrente</donate_currentmonth_title><donate_lastmonth_title>Mese scorso</donate_lastmonth_title><donate_anonym>Anonimo</donate_anonym><donate_anonym_donatenotice>Non dimenticarti di specificare un nome da mostrare vicino alla donazione se non vuoi donare anonimamente.</donate_anonym_donatenotice><donate_donatorlist_donationamount>{1} donazione(i)</donate_donatorlist_donationamount></donate>
