<?xml version="1.0"?>
<signature createdate="2010-11-14 16:06:24 / 1289750784"><signature_pic_lvlsea>Mare</signature_pic_lvlsea><signature_pic_lvlland>Terra</signature_pic_lvlland><signature_slots>Personaggio {1}</signature_slots><signature_selectlang_title>Lingua:</signature_selectlang_title><signature_selectlang_default>Predefinito: Lingua preferita dell'utente</signature_selectlang_default><signature_create_bcccode>BB-code (per forum)</signature_create_bcccode><signature_create_htmlcode>Codice HTML</signature_create_htmlcode><signature_create_subtitle>Firma: {1} creata da {2}</signature_create_subtitle><signature_instruction_howto>[b]Istruzioni per l'uso:[/b]&#xD;
Prima di tutto devi conoscere il numero di personaggi che vuoi mostrare nella tua firma.&#xD;
Scrivi i nomi dei tuoi personaggi nelle celle. (Non c'&#xE8; bisogno di riempirle tutte)&#xD;
A questo punto avrai un'anteprima di tutte le tue firme.&#xD;
&#xD;
Il numero di firme dipende se esiste un Template che supporta il numero di personaggi.&#xD;
Esempio: se vedi solamente tre firme e ne vorresti quattro, leggi il messaggio&#xD;
[i][url=http://florensia-forumurl/thread-3507.html]"How to create your own Signature"[/url][/i]&#xD;
e manda il tuo lavoro a un Admin o pubblicalo sul forum.&#xD;
</signature_instruction_howto><signature_instruction_advancedhint>[b]Suggerimento per utenti esperti:[/b]&#xD;
Puoi lasciare posti liberi tra le varie celle per avere uno spazio divisore.&#xD;
Puoi anche spostare i nomi per riordinare la visualizzazione dei tuoi personaggi nella firma.</signature_instruction_advancedhint><signature_slotsoverviewtitle>[b]Abbiamo:[/b]</signature_slotsoverviewtitle><signature_displayall>Mostra tutte le firme.</signature_displayall><signature_docreate>Crea la tua firma!</signature_docreate><signature_slotsoverviewrow>{1} modelli con {2} slot(s)</signature_slotsoverviewrow><signature_create_backgroundupload_error_notice>Il caricamento del background non &#xE8; avvenuto con successo.</signature_create_backgroundupload_error_notice><signature_create_savetemplate_error_notice>Si &#xE8; verificato un errore durante il salvataggio del tuo modello.</signature_create_savetemplate_error_notice><signature_create_template_error_notice>Il tuo modello ha qualche errore. Per favore riparalo in modo da poterlo salvare.</signature_create_template_error_notice><signature_create_characterslots_notice>Gli slots per definire i vostri personaggi saranno disponibili non appena saranno state creati i tag necessari &lt;char&gt;</signature_create_characterslots_notice><signature_create_characterslots_templateerror_notice>Gli spazi per definire i vostri personaggi saranno disponibili non appena verranno verificati i modelli</signature_create_characterslots_templateerror_notice><signature_create_signaturecode>Questo codice riguarda la firma che hai creato qui.</signature_create_signaturecode><signature_create_refresh>Aggiorna</signature_create_refresh><signature_create_popup_wheretouse>Dove usarlo:</signature_create_popup_wheretouse><signature_create_popup_madatorytags>Tag obbligatoria</signature_create_popup_madatorytags><signature_create_popup_optionaltags>Tag facoltativa:</signature_create_popup_optionaltags><signature_create_pagedescription>[b]In questo sito puoi creare la tua firma personale.[/b]&#xD;
Per favore modifica con attenzione il tuo modello poich&#xE9; non ci saranno backup e non verr&#xE0; cancellato.&#xD;
Se avete domande come provate a leggere [url=http://florensia-forumurl/thread-3507.html]"How to create your own Signature"[/url] nel forum e sentitevi liberi di fare domande.&#xD;
Dopo aver finito il modello &#xE8; possibile contattare un amministratore o pubblicarla direttamente sul forum. Se &#xE8; ben fatta e ottiene un buon feedback noi lo includeremo tra le firme ufficiali del generatore in modo che tutti gli utenti la possano usare!</signature_create_pagedescription><signature_create_backgroundupload>Carica un nuovo background:</signature_create_backgroundupload><signature_create_backgroundupload_data>Solamente gif, png o bmp - max. larghezza: 700px, max. altezza: 700px</signature_create_backgroundupload_data><signature_create_template_title>Template</signature_create_template_title><signature_create_colorpicker_title>Colorpicker</signature_create_colorpicker_title><signature_create_additionalobjects_title>Altri oggetti</signature_create_additionalobjects_title><signature_create_additionalobjects_notice>Sposta il cursore sopra il simbolo per ottenere maggiori informazioni</signature_create_additionalobjects_notice><signature_create_fonthelper_title>Font-Helper</signature_create_fonthelper_title><signature_create_getcoordinates>Clicca sull'immagine per ottenere le sue coordinate:</signature_create_getcoordinates></signature>
