<?xml version="1.0"?>
<donate createdate="2010-10-18 18:17:09 / 1287425829"><donate_donatorlist_title>Liste der Spender</donate_donatorlist_title><donate_notice>Die Webseite ist ein privates Projekt und kostet monatlich viel Geld um den Server zu betreiben und den Traffic zu bezahlen (rund {1}/Monat).&#xD;
Es w&#xE4;re sch&#xF6;n, wenn ein paar User nicht nur die Seite besuchen, sondern auch etwas spenden, um das Projekt weiterhin am Leben zu erhalten.&#xD;
Wenn du etwas beitragen m&#xF6;chtest, kannst du &#xFC;ber Paypal etwas spenden, indem du auf das Bild hier darunter klickst.&#xD;
Vielen Dank!</donate_notice><donate_donatorlist_date>[b]{1}[/b] von {2} am {3}</donate_donatorlist_date><donate_startpage_title>FloBase ist da, wenn du sie brauchst - Nun braucht FloBase dich!</donate_startpage_title><donate_startpage_donatetext>Ich m&#xF6;chte mich bei allen netten Spendern herzlich bedanken, denn das Ziel von 200&#x20AC; wurde erreicht und sogar weit &#xFC;berschritten!&#xD;
Eine Auflistung seht ihr auf der rechten Seite, geordnet nach Betrag und Zeitpunkt der Spende.&#xD;
F&#xFC;r weiteren Informationen, z.b. warum genau 200&#x20AC; und welcher neuer Server es sein wird, k&#xF6;nnt ihr den zugeh&#xF6;rigen Newseintrag im Forum lesen.&#xD;
&#xD;
Wer weiterhin noch etwas spenden m&#xF6;chte, kann dies gerne tun. Vergesst nicht euren Nicknamen anzugeben und ich werde euch so schnell wie m&#xF6;glich der Liste hinzuf&#xFC;gen.&#xD;
Nochmals: Vielen, vielen Dank!</donate_startpage_donatetext><donate_startpage_bottomnotice>Spenden werden nur f&#xFC;r FloBase verwendet und f&#xFC;r nichts anderes! [b]Sponsoren sind auch willkommen![/b] Kontakt webmaster[at]florensia-base[dot]com.</donate_startpage_bottomnotice><donate_paypalfees>Paypal Geb&#xFC;hren</donate_paypalfees><donate_linktodonatepage>Du magst Florensia Base? - Bitte unterst&#xFC;tze uns durch eine Spende.</donate_linktodonatepage><donate_currentmonth_title>Aktueller Monat</donate_currentmonth_title><donate_lastmonth_title>Letzer Monat</donate_lastmonth_title><donate_anonym>Anonym</donate_anonym><donate_anonym_donatenotice>Vergiss nicht, einen Namen in der zus&#xE4;tzlichen Notizbox anzugeben, sofern du nicht anonym spenden m&#xF6;chtest.</donate_anonym_donatenotice><donate_donatorlist_donationamount>{1} Spende(n)</donate_donatorlist_donationamount></donate>
