<?xml version="1.0"?>
<signature createdate="2010-04-29 18:19:59 / 1272557999"><signature_pic_lvlsea>Mer</signature_pic_lvlsea><signature_pic_lvlland>Terre</signature_pic_lvlland><signature_slots>Personnage {1}</signature_slots><signature_selectlang_title>Langue :</signature_selectlang_title><signature_selectlang_default>Par d&#xE9;faut : Langue de navigation sur FloBase</signature_selectlang_default><signature_create_bcccode>BB-Code</signature_create_bcccode><signature_create_htmlcode>HTML-Code</signature_create_htmlcode><signature_create_subtitle>Signature: {1} cr&#xE9;&#xE9;e par {2}</signature_create_subtitle><signature_instruction_howto>[b]Comment l'utiliser:[/b]&#xD;
-Inscrivez le nom de votre(vos) personnage(s)dans les cases. (Vous n'&#xEA;tes pas oblig&#xE9;s de tous les remplir)&#xD;
-Ensuite, s&#xE9;lectionnez une langue d'affichage.&#xD;
-Cliquez sur : Cr&#xE9;er votre signature!&#xD;
Vous obtiendrez alors un aper&#xE7;u de toutes les signatures disponibles!&#xD;
&#xD;
La quantit&#xE9; de case Personnage d&#xE9;pend du template. Certains templates peuvent avoir 1-2-3 Case Personnage. &#xD;
Si vous voulez un template sp&#xE9;cifique, mais que la quantit&#xE9; de Case Personnage est limit&#xE9; &#xE0; 3 et que vous en voudriez 4, alors lisez le sujet&#xD;
[i][url=http://forum.florensia-base.com/thread-3539.html]"Comment cr&#xE9;er votre propre signature personalis&#xE9;e"[/url][/i]&#xD;
et envoyez le &#xE0; un Admin ou bien postez le sur le forum.&#xD;
&#xD;
** Votre signature sera automatiquement mise &#xE0; jour au cours de la nuit. Un petit d&#xE9;calage entre le niveau affich&#xE9; et votre niveau actuel est possible...&#xD;
</signature_instruction_howto><signature_instruction_advancedhint>[b]Astuce pour les utilisateurs avanc&#xE9;s:[/b]&#xD;
Il est possible de laisser des Cases Personnage vide pour cr&#xE9;er des "espaces".&#xD;
Aussi, vous pouvez inter-changer  des noms pour r&#xE9;ordonner l'ordre de vos personnages dans votre signature.</signature_instruction_advancedhint><signature_slotsoverviewtitle>[b]Actuellement disponible : [/b]</signature_slotsoverviewtitle><signature_displayall>Afficher toutes les signatures, m&#xEA;me celles avec plus de Case Personnage.</signature_displayall><signature_docreate>Cr&#xE9;er votre signature!</signature_docreate><signature_slotsoverviewrow>{1} Templates avec {2} Case(s) Personnage</signature_slotsoverviewrow><signature_create_backgroundupload_error_notice>Le t&#xE9;l&#xE9;chargement de votre arri&#xE8;re-plan a &#xE9;chou&#xE9;.&#xD;
</signature_create_backgroundupload_error_notice><signature_create_savetemplate_error_notice>Une erreur est survenue en tentant de sauvegarder votre template.</signature_create_savetemplate_error_notice><signature_create_template_error_notice>Votre template contient certaines erreurs. Corrigez les afin qu'il puisse &#xEA;tre sauvegard&#xE9;.&#xD;
</signature_create_template_error_notice><signature_create_characterslots_notice>Les Cases Personnage seront disponibles aussit&#xF4;t que vous aurez cr&#xE9;&#xE9; le tag n&#xE9;cessaire &lt;char&gt; .</signature_create_characterslots_notice><signature_create_characterslots_templateerror_notice>Les Cases Personnage seront disponibles aussit&#xF4;t que le template sera analys&#xE9;.</signature_create_characterslots_templateerror_notice><signature_create_signaturecode>Ce code redirigera en tout temps vers la signature que vous avez r&#xE9;alis&#xE9; ici.</signature_create_signaturecode><signature_create_refresh>Actualiser</signature_create_refresh><signature_create_popup_wheretouse>O&#xF9; l'ins&#xE9;rer:</signature_create_popup_wheretouse><signature_create_popup_madatorytags>Tag obligatoire</signature_create_popup_madatorytags><signature_create_popup_optionaltags>Tags optionels:</signature_create_popup_optionaltags><signature_create_pagedescription>[b]Cr&#xE9;ez votre propre signature![/b]&#xD;
Merci de porter une attention particuli&#xE8;re lors de la r&#xE9;alisation de votre signature puisqu'il n'y a aucune sauvegarde ni de fonction de retour en arri&#xE8;re (annuler).&#xD;
Si vous avez besoin d'assistance, vous pouvez consulter le sujet  [url=http://forum.florensia-base.com/thread-3539.html]"Comment cr&#xE9;er votre propre signature personalis&#xE9;e"[/url] sur le forum et y poster vos questions.&#xD;
Une fois votre template termin&#xE9;, vous pouvez contacter un administrateur ou le publier directement sur le forum vous-m&#xEA;me. S'il est bien r&#xE9;alis&#xE9; et joli :P, nous pourrons tr&#xE8;s certainement l'ajouter &#xE0; notre [url=http://fr.florensia-base.com/sigcreate.php] g&#xE9;n&#xE9;rateur de signatures[/url] afin que tous les utilisateurs puissent l'utiliser.&#xD;
</signature_create_pagedescription><signature_create_backgroundupload>T&#xE9;l&#xE9;charger un nouvel arri&#xE8;re-plan :</signature_create_backgroundupload><signature_create_backgroundupload_data>Seulement gif, png ou jpg - longueur max: 700px, hauteur max: 700px</signature_create_backgroundupload_data><signature_create_template_title>Template</signature_create_template_title><signature_create_colorpicker_title>S&#xE9;lection de couleurs</signature_create_colorpicker_title><signature_create_additionalobjects_title>Objets additionnels disponibles</signature_create_additionalobjects_title><signature_create_additionalobjects_notice>Survolez l'objet avec votre souris pour plus d'informations</signature_create_additionalobjects_notice><signature_create_fonthelper_title>Liste des polices d'&#xE9;criture</signature_create_fonthelper_title><signature_create_getcoordinates>Cliquez &#xE0; un endroit sur l'image pour obtenir les coordonn&#xE9;es pr&#xE9;cises de cet emplacement :&#xD;
</signature_create_getcoordinates></signature>
