<?xml version="1.0"?>
<donate createdate="2010-10-18 18:14:31 / 1287425671"><donate_donatorlist_title>Liste des g&#xE9;n&#xE9;reux donateurs</donate_donatorlist_title><donate_notice>Ce site web est un projet priv&#xE9; ( non affili&#xE9; avec le site officiel de Florensia) et une somme consid&#xE9;rable est requise pour payer l'h&#xE9;bergement et la bande passante (environ {1}/mois).&#xD;
Nous serions extr&#xEA;mement ravis si, en plus de visiter le site, les utilisateurs pouvaient &#xE9;galement supporter ce projet pour le maintenir en vie le plus longtemps possible.&#xD;
Un don via Paypal, peu importe le montant, serait &#xE9;norm&#xE9;ment appr&#xE9;ci&#xE9;. Merci!</donate_notice><donate_donatorlist_date>[b]{1}[/b] par {2} le {3}</donate_donatorlist_date><donate_startpage_title>FloBase est l&#xE0; quand vous en avez besoin &#x2013; Aujourd&#x2019;hui c&#x2019;est FloBase qui a besoin de vous !</donate_startpage_title><donate_startpage_donatetext>Je souhaite remercier tout les g&#xE9;n&#xE9;reux donateurs - La somme de 200&#x20AC; a &#xE9;t&#xE9; atteinte et m&#xEA;me d&#xE9;pass&#xE9;.&#xD;
La liste des donateurs a votre droite, est class&#xE9;e selon la somme de la donation et la date.&#xD;
Pour plus d'informations, par exemple: pourquoi nous avons besoin de 200&#x20AC; et quel serveur arrive sous peu, vous pouvez lire l'annonce (nouvelle) sur le forum.&#xD;
&#xD;
Si quelqu'un veut faire une donation, n'oubliez pas de marquer votre pseudo sur la transaction et je vous mettrai dans la liste d&#xE8;s que possible.&#xD;
Merci beaucoup!&#xD;
</donate_startpage_donatetext><donate_startpage_bottomnotice>Les donations seront utilis&#xE9;es pour FloBase et rien d&#x2019;autre. [b]Les Sponsors Sont Les Bienvenues![/b] Contact webmaster[at]florensia-base[dot]com. (en anglais)</donate_startpage_bottomnotice><donate_paypalfees>Honoraires Paypal </donate_paypalfees><donate_linktodonatepage>You like Florensia Base? - Please support it by donating.</donate_linktodonatepage><donate_currentmonth_title>Current month</donate_currentmonth_title><donate_lastmonth_title>Last month</donate_lastmonth_title><donate_anonym>Anonym</donate_anonym><donate_anonym_donatenotice>Don't forget to specify a name to display within the additional note box if you don't want to donate anonymously.</donate_anonym_donatenotice><donate_donatorlist_donationamount>{1} donation(s)</donate_donatorlist_donationamount></donate>
