<?xml version="1.0"?>
<signature createdate="2009-11-25 13:05:17 / 1259150717"><signature_pic_lvlsea>Deniz</signature_pic_lvlsea><signature_pic_lvlland>Kara</signature_pic_lvlland><signature_slots>Karakter {1}</signature_slots><signature_selectlang_title>Dil:</signature_selectlang_title><signature_selectlang_default>Varsay&#x131;lan: kullan&#x131;c&#x131;n&#x131;n tercih etti&#x11F;i dil</signature_selectlang_default><signature_create_bcccode>BB-Kodu (forum i&#xE7;in)</signature_create_bcccode><signature_create_htmlcode>HTML-Kodu</signature_create_htmlcode><signature_create_subtitle>&#x130;mza: {2}'nin olu&#x15F;turdu&#x11F;u {1}</signature_create_subtitle><signature_instruction_howto>[b]Nas&#x131;l kulan&#x131;l&#x131;r:[/b]&#xD;
&#xD6;ncelikle imzan&#x131;zda ka&#xE7; karakter kullanaca&#x11F;&#x131;n&#x131;z&#x131; belirlemelisiniz.&#xD;
Karakter(ler)inizin isimlerini kutulara yaz&#x131;n.(Hepsini doldurmak zorunda de&#x11F;ilsiniz)&#xD;
G&#xF6;r&#xFC;necek dili se&#xE7;in.&#xD;
&#x130;mzan&#x131; olu&#x15F;tur! butonuna t&#x131;klay&#x131;n.&#xD;
Sonras&#x131;nda kulland&#x131;&#x11F;&#x131;n&#x131;z karakter say&#x131;s&#x131;na ba&#x11F;l&#x131; olacak fazlal&#x131;kta imza g&#xF6;r&#xFC;n&#xFC;mlerini g&#xF6;receksiniz.&#xD;
&#xD;
&#x130;mza g&#xF6;r&#xFC;n&#xFC;mlerinin fazlal&#x131;&#x11F;&#x131; var olan &#x15F;ablonlara g&#xF6;re de&#x11F;i&#x15F;ir.&#xD;
&#xD6;rn: En fazla 8 imzal&#x131;k &#x15F;ablon var ve 9 karakteriniz varsa a&#x15F;a&#x11F;&#x131;daki konuyu okuyun.&#xD;
[i][url=http://florensia-forumurl/thread-3507.html]"Nas&#x131;l &#x130;mza Olu&#x15F;turulur (&#x130;ngilizce)"[/url][/i]&#xD;
ve &#xE7;al&#x131;&#x15F;man&#x131;z&#x131; site y&#xF6;neticisine g&#xF6;nderin ya da forumda yay&#x131;nlay&#x131;n.&#xD;
&#xD;
** &#x130;mzalar&#x131;n&#x131;z otomatik olarak geceye yak&#x131;n bir zamanda g&#xFC;ncellenir. G&#xF6;r&#xFC;nen levelle ger&#xE7;ek leveliniz aras&#x131;ndaki fark&#x131;n kalkmas&#x131; i&#xE7;in biraz gecikme olabilir.&#xD;
</signature_instruction_howto><signature_instruction_advancedhint>[b]&#x130;leri d&#xFC;zey kullan&#x131;c&#x131;lar&#x131; i&#xE7;in ipucu:[/b]&#xD;
"placeholder" olu&#x15F;turmak isterseniz karakterler aras&#x131; slotlar&#x131; bo&#x15F; b&#x131;rakabilirsiniz.&#xD;
B&#xF6;ylelikle imzan&#x131;zda karakterler aras&#x131; g&#xF6;r&#xFC;n&#xFC;m&#xFC; kolayca de&#x11F;i&#x15F;tirebilirsiniz.</signature_instruction_advancedhint><signature_slotsoverviewtitle>[b]&#x15E;ablonlar:[/b]</signature_slotsoverviewtitle><signature_displayall>Fazla slot olsa bile t&#xFC;m imzalar&#x131; g&#xF6;ster</signature_displayall><signature_docreate>&#x130;mzan&#x131; olu&#x15F;tur!</signature_docreate><signature_slotsoverviewrow>{1} &#x15E;ablon - {2} slota sahip</signature_slotsoverviewrow><signature_create_backgroundupload_error_notice>Arka zeminin y&#xFC;klenmesinde sorun &#xE7;&#x131;kt&#x131;.</signature_create_backgroundupload_error_notice><signature_create_savetemplate_error_notice>&#x15E;ablonu kaydederken bir hata olu&#x15F;tu.</signature_create_savetemplate_error_notice><signature_create_template_error_notice>&#x15E;ablonunuzda birka&#xE7; hata var. L&#xFC;tfen d&#xFC;zeltin ki kaydedilebilsin.</signature_create_template_error_notice><signature_create_characterslots_notice>Slots to specify your characters will be available as soon as you create the needed &lt;char&gt; tags</signature_create_characterslots_notice><signature_create_characterslots_templateerror_notice>Slots to specify your characters will be available as soon as the template can be parsed</signature_create_characterslots_templateerror_notice><signature_create_signaturecode>This code will always point to your signature you have created here.</signature_create_signaturecode><signature_create_refresh>Yenile</signature_create_refresh><signature_create_popup_wheretouse>Nerede kullanaca&#x11F;&#x131;n&#x131;z:</signature_create_popup_wheretouse><signature_create_popup_madatorytags>Mecburi etiketler</signature_create_popup_madatorytags><signature_create_popup_optionaltags>&#x130;ste&#x11F;e ba&#x11F;l&#x131; etiketler:</signature_create_popup_optionaltags><signature_create_pagedescription>[b]Bu sitede kendi imza &#x15F;ablonunuzu olu&#x15F;turabilirsiniz.[/b]&#xD;
L&#xFC;tfen &#x15F;ablonunuzu dikkatlice d&#xFC;zenleyin. &#xC7;&#xFC;nk&#xFC; yedekleme ve geri alma se&#xE7;enekleri yoktur.&#xD;
E&#x11F;er nas&#x131;l &#xE7;al&#x131;&#x15F;t&#x131;&#x11F;&#x131;na dair herhangi bir sorunuz varsa [url=http://florensia-forumurl/thread-3507.html]"Kendi imzan&#x131;z&#x131; olu&#x15F;turun (&#x130;ngilizce)"[/url] forumuna bak&#x131;n.&#xD;
&#x15E;ablonunuzu bitirince site y&#xF6;neticisi ile irtibata ge&#xE7;ebilir ya da kendiniz forumda yay&#x131;nlayabilirsiniz. E&#x11F;er g&#xFC;zel yap&#x131;lm&#x131;&#x15F; bir imza ise ve geri d&#xF6;n&#xFC;&#x15F; alabilirsek resmi imza olu&#x15F;turucunun i&#xE7;ine dahil edebiliriz ki herkes bu &#x15F;ablonu kullanabilsin.</signature_create_pagedescription><signature_create_backgroundupload>Yeni bir arka zemin resmi y&#xFC;kleyin:</signature_create_backgroundupload><signature_create_backgroundupload_data>Sadece gif, png veya jpg - max. geni&#x15F;lik: 700px, max. y&#xFC;kseklik: 700px</signature_create_backgroundupload_data><signature_create_template_title>&#x15E;ablon</signature_create_template_title><signature_create_colorpicker_title>RenkSe&#xE7;ici</signature_create_colorpicker_title><signature_create_additionalobjects_title>Ek nesneler m&#xFC;mk&#xFC;nd&#xFC;r</signature_create_additionalobjects_title><signature_create_additionalobjects_notice>Daha fazla bilgi i&#xE7;in fareyi sembollerin &#xFC;zerine s&#xFC;r&#xFC;kleyin</signature_create_additionalobjects_notice><signature_create_fonthelper_title>Font-Yard&#x131;mc&#x131;s&#x131;</signature_create_fonthelper_title><signature_create_getcoordinates>Tam kordinatlar i&#xE7;in resime t&#x131;klay&#x131;n:</signature_create_getcoordinates></signature>
