<?xml version="1.0"?>
<signature createdate="2009-11-12 18:35:48 / 1258047348"><signature_pic_lvlsea>Sea</signature_pic_lvlsea><signature_pic_lvlland>Land</signature_pic_lvlland><signature_slots>Personaje {1}</signature_slots><signature_selectlang_title>Idioma :</signature_selectlang_title><signature_selectlang_default>Predeterminado : Idioma de navegaci&#xF3;n FloBase</signature_selectlang_default><signature_create_bcccode>BB-Code</signature_create_bcccode><signature_create_htmlcode>HTML-Code</signature_create_htmlcode><signature_create_subtitle>Firma : {1} creada por {2}</signature_create_subtitle><signature_instruction_howto>[b] C&#xF3;mo usar: [/b]&#xD;
-Introduce el nombre de tu (s) personaje (s) en las casillas. (No tienes porque ponerlos todos)&#xD;
-A continuaci&#xF3;n, selecciona un idioma de visualizaci&#xF3;n.&#xD;
-Haz clic en: Crea tu firma!&#xD;
Obtendr&#xE1;s una visi&#xF3;n general de todas las firmas!&#xD;
&#xD;
La cantidad depende si las plantillas admiten mas de un personaje. Las plantillas pueden tener 1-2-3 personajes.&#xD;
Si quieres una firma con 4 personajes o mas, deberas crear tu firma propia, para aprender por favor dirigete a nuestro foro [i][url=http://florensia-forumurl/thread-3507.html]"How to create your own Signature"[/url] (En ingl&#xE9;s)[/i]&#xD;
y enviarlo a un administrador o por correo en el foro.&#xD;
&#xD;
** Tu firma se actualizar&#xE1; autom&#xE1;ticamente durante la noche. Una peque&#xF1;a discrepancia entre la muestra y tu nivel actual es posible ...&#xD;
 </signature_instruction_howto><signature_instruction_advancedhint>[b] Sugerencia para usuarios avanzados: [/b]&#xD;
Puedes dejar en blanco las casillas de jugadores para crear "espacios".&#xD;
Tambi&#xE9;n, puedes cambiar los nombres para reordenar el orden de los personajes de su firma. </signature_instruction_advancedhint><signature_slotsoverviewtitle>[b] disponibles en la actualidad : [/b]</signature_slotsoverviewtitle><signature_displayall>Ver todas las firmas, incluso aquellas con mas personajes.</signature_displayall><signature_docreate>Crea tu firma !</signature_docreate><signature_slotsoverviewrow>{1} Plantillas para {2} personajes</signature_slotsoverviewrow><signature_create_backgroundupload_error_notice>No fue posible a&#xF1;adir tu background.</signature_create_backgroundupload_error_notice><signature_create_savetemplate_error_notice>Ocurrio un error intentando guardar tu plantilla.</signature_create_savetemplate_error_notice><signature_create_template_error_notice>Tu plantilla contiene errores. Por favor corrigelos y vuelve a intentar guardarla.</signature_create_template_error_notice><signature_create_characterslots_notice>Slots to specify your characters will be available as soon as you create the needed &lt;char&gt; tags</signature_create_characterslots_notice><signature_create_characterslots_templateerror_notice>Slots to specify your characters will be available as soon as the template can be parsed</signature_create_characterslots_templateerror_notice><signature_create_signaturecode>This code will always point to your signature you have created here.</signature_create_signaturecode><signature_create_refresh>Actualizar</signature_create_refresh><signature_create_popup_wheretouse>Donde utilizar:</signature_create_popup_wheretouse><signature_create_popup_madatorytags>Tags obligatorios</signature_create_popup_madatorytags><signature_create_popup_optionaltags>tags opcionales:</signature_create_popup_optionaltags><signature_create_pagedescription>[b]En esta p&#xE1;gina podras crear tu propia firma.[/b]&#xD;
Por favor, modifica tu plantilla con cuidado porque no se har&#xE1;n copias de seguridad y no se puede deshacer.&#xD;
Si tienes alguna pregunta de c&#xF3;mo funciona todo esto, lee [url=http://florensia-forumurl/thread-3507.html]"How to create your own Signature"[/url] en el foro y no dude en preguntar. (En ingles)&#xD;
Cuando termines tu plantilla puedes contactar a un administrador o publicarlo en el foro mismo. Si est&#xE1; bien hecha y obtiene buena critica se incluir&#xE1; al generador de firmas oficial para que todos los usuarios puedan usarla!</signature_create_pagedescription><signature_create_backgroundupload>Subir un nuevo background:</signature_create_backgroundupload><signature_create_backgroundupload_data>Solo gif, png or jpg - max. width: 700px, max. height: 700px</signature_create_backgroundupload_data><signature_create_template_title>Plantilla</signature_create_template_title><signature_create_colorpicker_title>Colorpicker</signature_create_colorpicker_title><signature_create_additionalobjects_title>Objetos adicionales</signature_create_additionalobjects_title><signature_create_additionalobjects_notice>Coloque el cursor sobre los s&#xED;mbolos para obtener m&#xE1;s informaci&#xF3;n</signature_create_additionalobjects_notice><signature_create_fonthelper_title>Font-Ayuda</signature_create_fonthelper_title><signature_create_getcoordinates>Click en la imagen para obtener las coordinadas exactas:</signature_create_getcoordinates></signature>
