<?xml version="1.0"?>
<signature createdate="2009-06-09 21:23:18 / 1244575398"><signature_pic_lvlsea>See</signature_pic_lvlsea><signature_pic_lvlland>Land</signature_pic_lvlland><signature_slots>Charakter {1}</signature_slots><signature_selectlang_title>Sprache:</signature_selectlang_title><signature_selectlang_default>Default: Bevorzugte Sprache des Betrachters</signature_selectlang_default><signature_create_bcccode>BBC-Code</signature_create_bcccode><signature_create_htmlcode>HTML-Code</signature_create_htmlcode><signature_create_subtitle>Signatur: {1} erstellt von {2}</signature_create_subtitle><signature_instruction_howto>[b]Wie wird es benutzt:[/b]&#xD;
Zuerst musst du wissen, wieviele Charakter du auf der Signatur anzeigen lassen willst.&#xD;
Schreibe die Namen der Charakter in die Boxen; du musst nicht alle ausf&#xFC;llen.&#xD;
Danach wirst du eine &#xDC;bersicht von Signaturen sehen, die die gew&#xFC;nschte Anzahl an Pl&#xE4;tzen oder mehr haben.&#xD;
&#xD;
Die Anzahl der Boxen h&#xE4;ngt davon ab, ob es eine Signatur gibt, die die Anzahl der Charakter unterst&#xFC;tzt.&#xD;
Wenn z.b. nur drei Boxen angezeigt werden, du aber eine Signatur mit vier oder mehr Charakteren haben m&#xF6;chtest, lese dir den Artikel [i][url=http://florensia-forumurl/thread-3928.html]"Wie erstelle ich meine eigene Signatur?"[/url][/i] durch und sende deine Arbeit einem Administrator zu oder publiziere es in unserem Forum.&#xD;
</signature_instruction_howto><signature_instruction_advancedhint>[b]Tipp:[/b]&#xD;
Du kannst zwischen Charakteren freie Boxen lassen, um so einen "Platzhalter" zu bekommen.&#xD;
Ausserdem kannst du die Namen vertauschen, um so die Anordnung auf der Signatur zu ver&#xE4;ndern.</signature_instruction_advancedhint><signature_slotsoverviewtitle>[b]Wir haben:[/b]</signature_slotsoverviewtitle><signature_displayall>Zeige auch Signaturen mit mehr Pl&#xE4;tzen</signature_displayall><signature_docreate>Erstelle deine Signatur!</signature_docreate><signature_slotsoverviewrow>{1} Templates mit {2} Pl&#xE4;tzen</signature_slotsoverviewrow><signature_create_backgroundupload_error_notice>Das Hochladen deines Hintergrundbildes war nicht erfolgreich.</signature_create_backgroundupload_error_notice><signature_create_savetemplate_error_notice>Ein Fehler trat auf beim Speichern deines Templates.</signature_create_savetemplate_error_notice><signature_create_template_error_notice>Dein Template ist fehlerhaft. Behebe zuerst die Fehler, damit es gespeichert werden kann.</signature_create_template_error_notice><signature_create_characterslots_notice>Eingabefelder um deine Charakter anzugeben werden, sobald du die n&#xF6;tigen &lt;char&gt; Tags erstellst hast, erscheinen</signature_create_characterslots_notice><signature_create_characterslots_templateerror_notice>Eingabefelder um deine Charakter anzugeben werden erscheinen, sobald dein Template gelesen werden kann</signature_create_characterslots_templateerror_notice><signature_create_signaturecode>Dieser Kode wird immer auf die hier erstellte Signatur verweisen.</signature_create_signaturecode><signature_create_refresh>Erneuern</signature_create_refresh><signature_create_popup_wheretouse>Wo zu benutzen:</signature_create_popup_wheretouse><signature_create_popup_madatorytags>Pflichttags</signature_create_popup_madatorytags><signature_create_popup_optionaltags>Zus&#xE4;tzliche Tags:</signature_create_popup_optionaltags><signature_create_pagedescription>[b]Auf dieser Seite kannst du deine eigene Signatur erstellen.[/b]&#xD;
Bearbeite dein Template mit Vorsicht, denn es werden keine Backups erstellt und es gibt kein "zur&#xFC;ck"-Knopf.&#xD;
Wenn du Fragen hast, wie alles funktioniert, lese dir zuerst [url=http://florensia-forumurl/thread-3928.html]"Wie erstelle ich meine eigene Signatur?"[/url] im Forum durch.&#xD;
Wenn du dein Template fertiggestellt hast und es gerne auch anderen zur Verf&#xFC;gung stellen m&#xF6;chtest, wende dich entweder an einen Administrator oder stelle deine Arbeit ins Forum.&#xD;
Wenn dein Template sch&#xF6;n gemacht ist und viele daf&#xFC;r abstimmen, werden wir es in die offizielle Liste einf&#xFC;gen, sodass alle User es ausw&#xE4;hlen k&#xF6;nnen!</signature_create_pagedescription><signature_create_backgroundupload>Neues Bild hochladen:</signature_create_backgroundupload><signature_create_backgroundupload_data>Nur gif, png or jpg - max. Breite: 700px, max. H&#xF6;he: 700px</signature_create_backgroundupload_data><signature_create_template_title>Template</signature_create_template_title><signature_create_colorpicker_title>Farbauswahl-Helfer</signature_create_colorpicker_title><signature_create_additionalobjects_title>Zus&#xE4;tzliche Objekte</signature_create_additionalobjects_title><signature_create_additionalobjects_notice>Fahre &#xFC;ber die Symbole um die Details einzublenden.</signature_create_additionalobjects_notice><signature_create_fonthelper_title>Schriftartauswahl-Helfer</signature_create_fonthelper_title><signature_create_getcoordinates>Klick auf das Bild um die Koordinaten anzuzeigen:</signature_create_getcoordinates></signature>
