<?xml version="1.0"?>
<donate createdate="2010-10-24 16:44:31 / 1287938671"><donate_donatorlist_title>Lista de generosos doadores</donate_donatorlist_title><donate_notice>Este website &#xE9; um projeto privado e custa bastante para manter o dom&#xED;nio e pagar pelo tr&#xE1;fego de dados (cerca de {1}/m&#xEA;s).&#xD;
Ficar&#xED;amos muito felizes se os usu&#xE1;rios n&#xE3;o s&#xF3; visitassem e usassem o site mas tamb&#xE9;m ajudassem, para que o projeto possa sobreviver.&#xD;
Seria fant&#xE1;stico se voc&#xEA; pudesse contribuir com algo via PayPal clicando na imagem abaixo. Obrigado!</donate_notice><donate_donatorlist_date>[b]{1}[/b] por {2} em {3}</donate_donatorlist_date><donate_startpage_title>FloBase est&#xE1; l&#xE1; se voc&#xEA; precisa dele - agora o FloBase precisa de voc&#xEA;!</donate_startpage_title><donate_startpage_donatetext>Gostaria muito de agradecer a todos os doadores - a meta de 200&#x20AC; foi alcan&#xE7;ada e at&#xE9; mesmo rompida.&#xD;
Uma lista com todos os doadores pode ser em contrada ao lado direito, ordenada pela quantidade e tempo da doa&#xE7;&#xE3;o.&#xD;
Para mais informa&#xE7;&#xF5;es, ex.: por que exatos 200&#x20AC; e o qual novo servidor ser&#xE1; usado, leia as not&#xED;cias no f&#xF3;rum.&#xD;
&#xD;
Se algu&#xE9;m quer doar algo mais, por favor n&#xE3;o esque&#xE7;a seu nick na transa&#xE7;&#xE3;o e colocarei voc&#xEA; na lista o mais cedo poss&#xED;vel.&#xD;
Repito: Muito obrigado!</donate_startpage_donatetext><donate_startpage_bottomnotice>Doa&#xE7;&#xF5;es ser&#xE3;o usadas para o FloBase e nada mais! [b]Patrocinadores s&#xE3;o bem-vindos![/b] Contate webmaster[at]florensia-base[dot]com. (em ingl&#xEA;s)</donate_startpage_bottomnotice><donate_paypalfees>Taxas do PayPal</donate_paypalfees><donate_linktodonatepage>Voc&#xEA; gosta do Florensia Base? - Por favor doe e ajude!</donate_linktodonatepage><donate_currentmonth_title>Esse m&#xEA;s</donate_currentmonth_title><donate_lastmonth_title>M&#xEA;s passado</donate_lastmonth_title><donate_anonym>An&#xF4;nimo</donate_anonym><donate_anonym_donatenotice>N&#xE3;o esque&#xE7;a de especificar um nome para mostrar dentro da caixa nota adicional se voc&#xEA; n&#xE3;o quer doar anonimamente.</donate_anonym_donatenotice><donate_donatorlist_donationamount>{1} doa&#xE7;&#xE3;o(&#xF5;es)</donate_donatorlist_donationamount></donate>
