<?xml version="1.0"?>
<signature createdate="2009-12-06 18:35:14 / 1260120914"><signature_pic_lvlsea>Mar</signature_pic_lvlsea><signature_pic_lvlland>Terra</signature_pic_lvlland><signature_slots>Personagem {1}</signature_slots><signature_selectlang_title>Idioma:</signature_selectlang_title><signature_selectlang_default>Padr&#xE3;o: idioma preferido do usu&#xE1;rio</signature_selectlang_default><signature_create_bcccode>BB-Code (uso no f&#xF3;rum)</signature_create_bcccode><signature_create_htmlcode>C&#xF3;digo HTML</signature_create_htmlcode><signature_create_subtitle>Assinatura: {1} criado por {2}</signature_create_subtitle><signature_instruction_howto>[b]Como usar:[/b]&#xD;
Primeiramente, voc&#xEA; precisa saber quantos personagens gostaria de mostrar na sua assinatura.&#xD;
Digite o nome dos seus personagens nas caixas de texto. (Voc&#xEA; nao precisa preencher todas)&#xD;
Selecione um idioma.&#xD;
Clique em: Crie sua assinatura!&#xD;
Depois disso voc&#xEA; ter&#xE1; uma vis&#xE3;o geral de todas as assinaturas que tenham o n&#xFA;mero de espa&#xE7;os especificado ou mais.&#xD;
&#xD;
A quantidade de caixas de texto depende se h&#xE1; um modelo dispon&#xED;vel que suporte a quantidade de personagens.&#xD;
Ex: Se houverem apenas tr&#xEA;s espa&#xE7;os dispon&#xED;veis e voc&#xEA; gostaria de uma assinatura com quatro ou mais espa&#xE7;os por favor leia o post [i][url=http://florensia-forumurl/thread-4597.html]"Como criar sua pr&#xF3;pria assinatura"[/url][/i] e envie seu trabalho a um administrador ou publique em nosso forum.&#xD;
&#xD;
** Sua assinatura ser&#xE1; automaticamente atualizada durante a noite. Pode ocorrer uma diferen&#xE7;a entre o n&#xED;vel mostrado e o seu n&#xED;vel atual.</signature_instruction_howto><signature_instruction_advancedhint>[b]Dica para usu&#xE1;rios avan&#xE7;ados:[/b]&#xD;
Voc&#xEA; pode deixar espa&#xE7;os vazios entre personagens para criar um "lugar vago".&#xD;
Tamb&#xE9;m pode trocar os nomes para reordenar seus personagens na assinatura.</signature_instruction_advancedhint><signature_slotsoverviewtitle>[b]N&#xF3;s temos:[/b]</signature_slotsoverviewtitle><signature_displayall>Mostrar todas as assinaturas, mesmo as que t&#xEA;m mais slots</signature_displayall><signature_docreate>Crie sua assinatura!</signature_docreate><signature_slotsoverviewrow>{1} Modelos(s) com {2} espa&#xE7;o(s)</signature_slotsoverviewrow><signature_create_backgroundupload_error_notice>O upload da imagem de fundo falhou.</signature_create_backgroundupload_error_notice><signature_create_savetemplate_error_notice>Ocorreu um erro enquanto o modelo era salvo.</signature_create_savetemplate_error_notice><signature_create_template_error_notice>Seu modelo cont&#xE9;m alguns erros. Por favor conserte-os para que eu possa salv&#xE1;-lo.</signature_create_template_error_notice><signature_create_characterslots_notice>Espa&#xE7;os para especificar seus personagens estar&#xE3;o dispon&#xED;veis assim que voc&#xEA; criar as tags &lt;char&gt; necess&#xE1;rias</signature_create_characterslots_notice><signature_create_characterslots_templateerror_notice>Espa&#xE7;os para especificar seus personagens estar&#xE3;o dispon&#xED;veis assim que seu modelo seja analisado.</signature_create_characterslots_templateerror_notice><signature_create_signaturecode>Este c&#xF3;digo ir&#xE1; sempre apontar para sua assinatura criada aqui.</signature_create_signaturecode><signature_create_refresh>Atualizar</signature_create_refresh><signature_create_popup_wheretouse>Onde usar:</signature_create_popup_wheretouse><signature_create_popup_madatorytags>Tags obrigat&#xF3;rias</signature_create_popup_madatorytags><signature_create_popup_optionaltags>Tags opcionais</signature_create_popup_optionaltags><signature_create_pagedescription>[b]Neste site voc&#xEA; pode criar sua pr&#xF3;pria assinatura.[/b]&#xD;
Por favor edite seu modelo com cuidado, pois n&#xE3;o ser&#xE3;o feitos backups e n&#xE3;o h&#xE1; como desfazer.&#xD;
Se voc&#xEA; tem d&#xFA;vidas sobre como tudo isso funciona leia no f&#xF3;rum [url=http://florensia-forumurl/thread-3507.html]"Como criar sua pr&#xF3;pria assinatura" (em ingl&#xEA;s)[/url] e fique a vontade para perguntar.&#xD;
Depois de terminado seu modelo voc&#xEA; pode entrar em contato com um administrador ou publicar, voc&#xEA; mesmo, no f&#xF3;rum. Se for bem feito e houver boa aceita&#xE7;&#xE3;o, iremos incluir no gerador de assinaturas oficial, para que todos os usu&#xE1;rios possam us&#xE1;-lo!</signature_create_pagedescription><signature_create_backgroundupload>Fazer upload de nova imagem de fundo:</signature_create_backgroundupload><signature_create_backgroundupload_data>Apenas gif, png ou jpg - largura m&#xE1;xima: 700 pixels, altura m&#xE1;xima: 700 pixels</signature_create_backgroundupload_data><signature_create_template_title>Modelo</signature_create_template_title><signature_create_colorpicker_title>Seletor de cor</signature_create_colorpicker_title><signature_create_additionalobjects_title>Objetos adicionais dispon&#xED;veis</signature_create_additionalobjects_title><signature_create_additionalobjects_notice>Mantenha o mouse sobre os s&#xED;mbolos para obter mais informa&#xE7;&#xF5;es</signature_create_additionalobjects_notice><signature_create_fonthelper_title>Amostra de fontes</signature_create_fonthelper_title><signature_create_getcoordinates>Clique na figura para obter as coordenadas:</signature_create_getcoordinates></signature>
